dist: trusty
language: java
before_install:
  - sudo apt-get install -qq liblzo2-dev
env:
  global:
  - C_INCLUDE_PATH=/usr/include/lzo LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
  - secure: odY2D6xmt38tl/5tznMyYiLvmXJQLdiXhfZGhP95kkgFPCOvSREH3W9kLonoE0llb1lTPKrffMtJopPuvd/2AuJdQSSC7s/ZO+0ZPz9P6tuxIdkx62B8q1sI7EJ0Y9OX1WYgw//oxDrWueEpXorAlpXfD/riNOZgwqwi2iy99OGr9FkI2u62LFQuZz7a14gZ3Fh5vNkK7dWWdSVos18KM4PjK7oIFKESV/sIgNWL4vLmmfvakfHMnXe2iWpKgJ06IFUpZa7NeWA7y2kITE+Qo2Ksjcl2nyXlo80mvPGpNT3AyF/c6wErA6UK9tinEJFxNSasb80xt1v3qSYfVHvpG5Jjazl65zIUhqANXRZGpwAF9Ow68qSNdtcWxhL4D8scqrAskmaf+AmQ9Uvkv80jHrxoch9wVk+b7eKBnyzWWk4jUvlYU3RMNAkppohnGQz+ezVwjo6/PoP6oDyOHgMf47tooC9ZqQvmRcT4yFc6gucGMfu9FsX0zucucbLIFP4vctydRK2rlsa2xXBt4Y+zMdcbD9sL7e7RKGvnLRslUBlL3zx512z12V3VYqFDhQKPCEOLtkovlRtW+w3aE2dnYYsxnlStsFg+CRPa8z0m4C4msBL4+GbMl/diwe/cMXXnOSC7vN1jY+OazjD3qx0MrkDyJYy0dpfWnByRvOFZt6o=
  - secure: jzOCZxaKg/IlpkseH21DJpOB8e+8uHgW9v4SuTA9qDVRleFlvtv589BZwgM1c6Qd5/msIb3xFnHDRUrguGd1KIoNhhhfLaAvyU+LLAUcbK5SxIMp59PwB9DkRwmt8fp/j5ZM3qh+tb1QYpH1ZsjRSkCzshRAny7+GOoq/YWdDvEAtDmb0ZeFGc+7lSrEh72cuiKmwXyy910kSZOou8ukMkxlsmii1G+ex+aJqkbF0NLMnT/SddKDQ+sHxxa5jZ9s4mt/a1YpaXCozMzf6B1/LYGsbvnteMMXTI7yFRVFliCwZ1ExumIM/3da9zG95XJohb5M+6KBqN5Du96jApWiKJhNp13b0JhbKpKHGrhjmJ1zoAn7ppElPrraS3wJ3wqOW35/e90Hj8wb7T079RdyQQ8NK16WN1HgiEMg2b3LjIn+Tdl3oSfbiAwfyNP7kePhMWAxB7LM6LNNFhbx8BY4QpQ24mO23NKq+YXX6/5sNoZ+eW1wG3zcdtJNE465x5d3yl2akDBtaXh5MwkLDkrBnUufl1nBZrzetisGcmOsh3bOGi6mT8h8qicFfKIfDRE+ykt9GfVSJMOFKJTIOoucy66BcN8aTQ9BjEn4f8xGoQxsEEYrG45jFNoFGiC8HyBxytH9Q9LSjlqdF49cSljo/DhFuujQhappPFef2gC6/8Q=
jdk:
  - oraclejdk8
script:
  - mvn test # build with hadoop 2 and test against hadoop 2
  - mvn test -P hadoop-old # build with hadoop 2 and test against hadoop 1
deploy:
  provider: script
  script: "cp .travis/mvn-settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true
    condition: '$(.travis/is_release_tag.sh hadoop_lzo $TRAVIS_TAG && [ $? -eq 0 ] && echo "Deploying hadoop-lzo")'
