dist: trusty
language: java
before_install:
  - sudo apt-get install -qq liblzo2-dev
env:
  global:
  - C_INCLUDE_PATH=/usr/include/lzo LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
jdk:
  - oraclejdk8
script:
  - mvn test # build with hadoop 2 and test against hadoop 2
  - mvn test -P hadoop-old # build with hadoop 2 and test against hadoop 1
deploy:
  provider: script
  script: "cp .travis/mvn-settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true
    condition: '$(.travis/is_release_tag.sh hadoop_lzo $TRAVIS_TAG && [ $? -eq 0 ] && echo "Deploying hadoop-lzo")'
